# Generated by Django 3.1.2 on 2020-10-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('hospitalid', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('hpd', models.BooleanField()),
                ('ckd', models.BooleanField()),
                ('dm', models.BooleanField()),
                ('htn', models.BooleanField()),
                ('hiv', models.BooleanField()),
                ('trans', models.BooleanField()),
                ('resrate', models.IntegerField()),
                ('heartrate', models.IntegerField()),
                ('spo', models.IntegerField()),
                ('ddimer', models.IntegerField(null=True)),
                ('cpk', models.IntegerField(null=True)),
                ('crp', models.IntegerField(null=True)),
                ('ldh', models.IntegerField(null=True)),
                ('tropo', models.FloatField(null=True)),
                ('ferr', models.IntegerField(null=True)),
                ('absolute', models.FloatField(null=True)),
                ('ctscan', models.IntegerField(null=True)),
                ('abg', models.IntegerField(null=True)),
            ],
        ),
    ]
